# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Caeden117
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: shell, glsl, hlsl, shaderlab
          plugin_languages_threshold: 0%
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 4
          
          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs
          plugin_wakatime_limit: 4
